../bin/demo_tripod_alt.out: demo_tripod_alt.cc
	mkdir -p ../bin
	g++ -o $@ $< -lgetfem -lboost_system -std=gnu++11 
../bin/demo_thermo_elasticity_electrical_coupling.out: demo_thermo_elasticity_electrical_coupling.cc
	mkdir -p ../bin
	g++ -o $@ $< -lgetfem -lboost_system -std=gnu++11
